name: rtmpose_tracker

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  
  # PyTorch 2.0 (Stable with CUDA 11.8 for GTX 1660 Ti)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8

  # Core Libraries
  - numpy=1.24.3       # Pinned to avoid version 2.0 conflicts
  - scipy
  - pandas
  - opencv
  - pillow
  - tqdm
  - matplotlib

  # IMPORTANT FIXES
  # We removed 'lap' and added 'lapx' in pip section (Works on Windows)

  - pip
  - pip:
      - lapx>=0.5.5           # Fixes 'lap' build error on Windows
      - chumpy
      - onnxruntime-gpu       # Essential for inference speed
      - openmim
      - mmengine
      - "mmcv>=2.0.1"
      - "mmdet>=3.1.0"
      - "mmpose>=1.1.0"
      - shapely
      - colorama
      - terminaltables
      - json_tricks
      - xtcocotools